### ISSUE TITLE
Follower Test Not Showing Live Scoring Information

### ISSUE THREAD

**Issue by dilliemillie** [CorMazz/dancer_test#42]
Standard Follower Test does not show Scoring Information while administering test
![dancexam follower results](https://github.com/user-attachments/assets/ba259dd3-d235-4a2a-bf22-afc7cf56f6c0)

**Comment by CorMazz** [comment]
This actually isn't a bug. You can choose to have live grading or not, and the current test definition has live grading set to False for the followers. I just changed it and restarted the servers for you to see the live grading. 

![image](https://github.com/user-attachments/assets/871777ee-d79a-4345-9547-5bf718985415)

**Comment by CorMazz** [comment]
https://github.com/CorMazz/dancer_test/blob/084a421b450868f73dc641a0ca45f2545d3e2a9c/test_definitions.yaml#L207
