### ISSUE TITLE
View Results Link in Emailed Results Doesn't Work

### ISSUE THREAD

**Issue by dilliemillie** [CorMazz/dancer_test#48]
Emailed Test Results have a hyperlink to View Results that doesn't work. 
https://github.com/user-attachments/assets/9d1d367f-7a56-4f01-9694-47d27c5dc55b

**Comment by CorMazz** [comment]
@dilliemillie This one is interesting. It works for sending messages from Gmail to Gmail. What email domain are you using? It could be that your SMTP server is scrubbing the email of all URLs to keep it safe.

**Comment by dilliemillie** [comment]
That example was through Yahoo mail. At risk of sounding like an unsafe online user - I click through links in emails semi regularly, so that shouldn't be the issue.
