### ISSUE TITLE
Consistent Scale Numbers?

### ISSUE THREAD

**Issue by dilliemillie** [CorMazz/dancer_test#61]
This is about the test itself and not the platform-

The numbers on the toggle button scales as designed on the test currently are unique to each testing element. That caused confusion for pros administering tests when one element goes 8-6-4-2-0 and another element goes 8-0-0-0-0 rather abruptly. The sliding scale options not being uniform makes the test slower and more confusing to administer.

**Comment by dilliemillie** [comment]
Obv this is a paper test problem too but I think the numbers are more obvious on the paper version than on the digital version

**Comment by dilliemillie** [comment]
Okay actually I administered a practice test just now and the scale numbers don't show on the toggle buttons. It wasn't always that way was it?

**Comment by CorMazz** [comment]
It is an option to show or not show point values and live grading when administering the test. It was requested that I turn this off. 

Please direct issues with the test definition itself to the Greenville Westies Board and then come to me separately with requests to change it. This isn't within the scope of this GitHub Repository.
